### ISSUE TITLE
Any chance of a Windows 10 version? 

### ISSUE THREAD

**Issue by TobiasDev** [sprout2000/lessview#2]
I use Windows (and linux) at work, and I like this app quite a lot, so I was just wondering if you have any plans on releasing it for Windows as well?

**Comment by sprout2000** [comment]
Thank you for your issue, Tobias.

I'm sorry but I don't have any plans on releaseing it for Windows so far because I don't have any code signing certificate for Windows.

If you have [Node.js](https://nodejs.org/en/) installed, you can build this app for yourself. It's so easy. like...

```
$ npm install
$ npm run package
```

and you'll find the installer in `release` directory.

Or you can just use Windows Photo App. It's better by far.

**Comment by TobiasDev** [comment]
Thanks for the answer! I'll close the issue since I got the answer I needed. :)
